### ISSUE TITLE
Event-titel geeft geen afvalsoort weer, maar datum

### ISSUE THREAD

**Issue by dvanp** [vwout/mijnafvalwijzer-to-ical#1]
Allereerst bedankt voor dit script, ideaal om te combineren met MagicMirror!
Bij mij is het resultaat echter nog niet optimaal: de titel van alle entries bevat alleen "Afval - datum" en niet de afvalsoort.

**Comment by vwout** [comment]
Leuk doel inderdaad!

De layout van de site is aangepast. Ik heb het script bijgewerkt, de titels en beschrijvingen zijn nu weer ingevuld als het goed is.
