### ISSUE TITLE
Huisnummer toevoegingen

### ISSUE THREAD

**Issue by Grendel7** [vwout/mijnafvalwijzer-to-ical#2]
Bedankt voor het maken van dit script, ik ben er heel blij mee!

Het enige waar ik tegenaan liep was dat het script geen huisnummer toevoegingen ondersteund.

Neem bijvoorbeeld het adres Grote Markt 43 C in Groningen. De bijbehorende webpagina daarvan is https://www.mijnafvalwijzer.nl/nl/9711LW/43/C/

Het script ondersteunt echter alleen de postcode en huisnummer, en in sommige gevallen levert dat geen correct werkend adres op. Het adres Grote Markt 43 bestaat bijvoorbeeld niet en geeft een 404 foutmelding.

De wijziging aan het script zijn volgens mij niet zo lastig (alleen een extra optionele parameter voor de URL), maar gezien het feit dat er van positionele argumenten gebruik wordt gemaakt is dat lastig.

**Comment by vwout** [comment]
Ik heb het script bijgewerkt zodat het nu ook werkt met huisnummer toevoegingen. Het is geen extra argument, maar je moet het direct aan het huisnummer toevoegen, dus `43C` gebruiken.

**Comment by Grendel7** [comment]
Super, dank je!

Ik weet alleen niet of dit bij alle toevoegingen goed gaat. Voor letters werkt dit wel, maar ik weet niet of er ook addressen zijn zoals Voorbeeldstraat 42 - 12.

Op deze pagina van het Kadaster lijkt dat dit namelijk wel kan: https://imbag.github.io/praktijkhandleiding/artikelen/mogen-slashes-of-streepjes-deel-uitmaken-van-de-huisnummertoevoeging-van-een-adres-in-de-bag

**Comment by vwout** [comment]
Waarschijnlik heb je gelijk. Ik heb proberen te testen hoe de API van MijnAfvalwijzer daar mee omgaat, maar al mijn (op zich wel bestaande) testadressen gaven geen resultaat. Dat kan komen doordat MijnAfvalwijzer niet voor die plaatsen wordt gebruikt, of doordat het adres voor MijnAfvalwijzer in dat geval gewoon 'Voorbeeldstraat 42' is. De toevoeging '-12' is waarschijnlijk een kamer- of appartementsnummer, in dat geval geldt het ophaalschema vanzelfsprekend voor het hele adres.
Als je een concreet adres weet dat wel werkt via de site, maar niet via het script, pas ik het graag aan.
