### ISSUE TITLE
2023 wordt niet opgehaald

### ISSUE THREAD

**Issue by wgroenewold** [vwout/mijnafvalwijzer-to-ical#3]
Om de data van 2023 op te halen moet er een POST request met form-data verstuurd worden. Ik dacht zelf aan iets van 

```
form_data = {'selectedYear': '2023'}
post = requests.post("https://www.mijnafvalwijzer.nl/site/year", data=form_data)
```

maar dat lijkt niet te werken. Als iemand me een zetje in de goede richting zou kunnen geven zou dat fijn zijn.

**Comment by wgroenewold** [comment]
Met deze URL haalt ie 2023 wel op:

https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=1234AB&street=&huisnummer=1&toevoeging=&app_name=afvalwijzer&platform=phone&mobiletype=android&afvaldata=2022-01-01&version=58&langs=nl

**Comment by vwout** [comment]
Als ik het goed zie wordt de data wel degelijk in de ical opgenomen, maar met het verkeerde jaar; het jaar in de ical is altijd het huidige jaar, dus 2022 nu. Dat is gefixt in de volgende commit.
