### ISSUE TITLE
Alarm component werkt niet + extra functionaliteit

### ISSUE THREAD

**Issue by mjaveld** [vwout/mijnafvalwijzer-to-ical#5]
Dit script heeft mij zeker al tijd bespaart, dus alvast bedankt!
Ik zou graag ook wat functionaliteit toevoegen. Wil het toch eerst even met jou checken voor ik begin.

### Probleem
Het begon met dat ik graag een melding kreeg van Google Calendar op een bepaalde tijd zodat ik niet vergeet 's avonds de bak buiten te moeten zetten. Het viel mij op dat er al een poging gedaan is om dat toe te voegen. 
https://github.com/vwout/mijnafvalwijzer-to-ical/blob/51354d34370d5f466123a49ac22efe09884f0696/mijnafvalwijzer-to-ical.py#L56-L58

Ik ben er even in gedoken en blijkbaar moet er nog een `DESCRIPTION` property toegevoegd worden. 
Zie: [iCalendar.org RFC](https://icalendar.org/iCalendar-RFC-5545/3-6-6-alarm-component.html) [Example](https://icalendar.org/iCalendar-RFC-5545/3-6-6-alarm-component.html#Example:~:text=such%20a%20case.-,Example,-The%20following%20example). Het gaat voornamelijk over de `dispprop`.
Heb het resulterende bestand van het script door de [iCalendar.org Validator](https://icalendar.org/validator.html) gegooid en daar komt  dezelfde melding uit: 
> Results:
File Size: 1857 lines, 37963 bytes
Number of events found: 154
Problem! Found 154 errors
Errors
Missing DESCRIPTION property in VALARM near line # 16
Reference: [RFC 5545 3.6.6. Alarm Component](http://icalendar.org/iCalendar-RFC-5545/3-6-6-alarm-component.html)

Om te valideren wat het moet zijn, heb ik in Google Calendar zelf een notificatie toegevoegd en de agenda weer ge-exporteert en door de validator gedaan. Die gaf geen fouten meer aan met de volgende datastructuur:
```
BEGIN:VEVENT
  DTSTART;VALUE=DATE:20231215
  DTEND;VALUE=DATE:20231216
  DTSTAMP:20231213T200124Z
  UID:2023-349-gft
  CREATED:20231213T183753Z
  DESCRIPTION:GFT 
  LAST-MODIFIED:20231213T184139Z
  SEQUENCE:0
  STATUS:CONFIRMED
  SUMMARY:Afval - GFT 
  TRANSP:OPAQUE

    BEGIN:VALARM
      ACTION:DISPLAY
      TRIGGER:-P0DT15H0M0S
      DESCRIPTION:This is an event reminder
    END:VALARM

END:VEVENT
```

### Oplossing
Hoewel de oplossing redelijk eenvoudig is, namelijk een lijntje code toevoegen, is de vraag of dit als standaard gedrag gewenst is.
Ik stel het volgende voor: 
- Extra argument voor het script genaamd `-alert`
   - Standaard 's ochtends 08:00
- Extra argument spatie-gescheiden na `-alert`
   - Net zoals met de selectie van afvalsoorten, comma-gescheiden, maar met `:` om tijd aan te geven.
      - Zoals `gft:0800,pmd:1700`
   - Gebruik van `-` voor de tijd om 1 dag van te voren de melding te krijgen
      - Zoals `gft:-2300,pmd:1700`
   - Makkelijk te parsen en dictionary met tijden van te maken. Lijkt veel op huidige optie voor afvalsoorten.

Voorbeelden van volledige commando:
- Standaard alert
   - `python mijnafvalwijzer-to-ical.py 3825AL 41 restafval,gft -alert`
- Eigen tijden (toevallig het schema wat ik graag zou willen)
   - `python mijnafvalwijzer-to-ical.py 3825AL 41 restafval,gft -alert restafval:-2000,gft:-2000,pmd:-2000,papier:1700`

### Afsluiting
Als je nog een verbetering hebt, laat het weten. 
Uiteraard ben ik bereid een pull-request te maken met de code.
😁

**Comment by vwout** [comment]
Hi Mike,

je voorstellen lijken me prima. Het is netter om standaard geen alert in de ical toe te voegen, maar dit afhankelijk te laten zijn van de aanwezigheid van een parameter. Het per categorie kunnen instellen van het moment waarop de herinnering komt is chic!

Doe maar een pull request :)

**Comment by mjaveld** [comment]
Ik had waarschijnlijk eerst even moeten google-en voordat ik begonnen was. Heb een werkende implementatie die bij het importeren dus niet werkt. Getest bij Google en Outlook Blijkbaar een bekent probleem en waarschijnlijk gedaan om spam te voorkomen in automatisch geupdatete agendas te voorkomen. 

https://stackoverflow.com/questions/35863320/valarms-from-icalendars-ics-not-being-recognized-by-google-calendar

Ik zie daarom geen reden om de code te mergen omdat het bijna compleet herschreven is. Dit voorkomt hopelijk ook dat er bugs geintroduceerd worden.

[Forked repo voor reference](https://github.com/mjaveld/mijnafvalwijzer-to-ical)

**Comment by vwout** [comment]
Spijtig. Hoewel Google er misschien niet direct iets beters mee doet, was het wel een goede suggestie voor verbetering, dank! Wellicht pak ik 'm alsnog wel op. Het gebruik van een echte argument parser is sowieso wel wat netter :)
